[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[project]
name = 'stickydesign-accel'
dependencies = ['numpy']
version = "0.9.0.a1"
authors = [ {name = "Constantine Evans", email = "const@costi.eu"} ]

[project.urls]
repository = "github.com/cgevans/stickydesign-accel"

[project.optional-dependencies]
test = [
     "pytest"
]

[tool.pytest.ini_options]
testpaths = ["tests"]